name: Submit IndexNow after Vercel deploy

on:
  deployment_status:

jobs:
  submit-indexnow:
    if: >-
      ${{ github.event.deployment_status.state == 'success' &&
          (github.event.deployment.environment == 'Production' || github.event.deployment.environment == 'production') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine app directory
        id: appdir
        shell: bash
        run: |
          if [ -f package.json ]; then
            echo "APP_DIR=." >> "$GITHUB_ENV"
          elif [ -f city-rules-website/package.json ]; then
            echo "APP_DIR=city-rules-website" >> "$GITHUB_ENV"
          else
            echo "::error::No package.json found at repo root or city-rules-website/"
            exit 1
          fi

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        working-directory: ${{ env.APP_DIR }}
        run: pnpm install --frozen-lockfile

      - name: Restore IndexNow cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.APP_DIR }}/.cache/indexnow.json
          key: indexnow-${{ github.sha }}
          restore-keys: |
            indexnow-

      - name: Submit URLs via IndexNow
        env:
          INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
          SITE_URL: https://www.cityrules.info
        run: pnpm run indexnow
        working-directory: ${{ env.APP_DIR }}

      - name: Save IndexNow cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.APP_DIR }}/.cache/indexnow.json
          key: indexnow-${{ github.sha }}
